version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:10"
      timezone: "Europe/Vienna"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:10"
      timezone: "Europe/Vienna"
