words = [
    "AGPL",
    "AKIAIOSFODNN",
    "ASAN",
    "Amz",
    "BITBUCKET",
    "BITRISE",
    "BUSL",
    "Bitbucket",
    "Bitrise",
    "CAS",
    "CDLA",
    "CIRCLECI",
    "CSP",
    "Cloudflare",
    "Codemagic",
    "DYLD",
    "Dto",
    "EUID",
    "FEMI",
    "IDAT",
    "IEND",
    "IHDR",
    "Jalr",
    "KPI",
    "Licensor",
    "NFS",
    "OOM",
    "RAII",
    "REPONAME",
    "RUSTFLAGS",
    "RUSTSEC",
    "SMB",
    "SOURCEBRANCHNAME",
    "Segoe",
    "TEAMCITY",
    "Untracks",
    "Utn",
    "WSL",
    "Zeroize",
    "Zmiri",
    "acb",
    "acd",
    "actionlint",
    "actuals",
    "afbe",
    "afbf",
    "alphanumerics",
    "atx",
    "baselined",
    "bbd",
    "bbeafaf",
    "bbox",
    "bcb",
    "bcbd",
    "beb",
    "bfe",
    "blopker",
    "breadthfirst",
    "bstr",
    "butteraugli",
    "bytemuck",
    "caed",
    "cafa",
    "cand",
    "cbb",
    "cdf",
    "cdylib",
    "ceec",
    "cfa",
    "chmod",
    "cinis",
    "cla",
    "cli",
    "clippy",
    "codecov",
    "cov",
    "dalek",
    "dcacd",
    "ddae",
    "ddba",
    "ddf",
    "defe",
    "dfbc",
    "dhash",
    "dify",
    "docstrings",
    "dotenv",
    "dssim",
    "dto",
    "dtolnay",
    "eba",
    "ebbea",
    "ebe",
    "ebf",
    "eecfd",
    "efc",
    "endfor",
    "esac",
    "fbde",
    "fcb",
    "fcd",
    "footgun",
    "geteuid",
    "getters",
    "gfm",
    "gha",
    "gitleaks",
    "gix",
    "gleon",
    "globbed",
    "globset",
    "goldens",
    "gpgsign",
    "idempotently",
    "indicatif",
    "keygen",
    "keypair",
    "kid",
    "kpi",
    "lcov",
    "learnings",
    "librustc",
    "lic",
    "lifecycle",
    "lookups",
    "lossy",
    "luma",
    "markdownlint",
    "memcmp",
    "minijinja",
    "miri",
    "mkdir",
    "mktemp",
    "mybucket",
    "mysecretpassword",
    "nextest",
    "nocapture",
    "norepo",
    "oninput",
    "oob",
    "phash",
    "pipefail",
    "pixelmatch",
    "powerset",
    "premultiply",
    "presign",
    "programmatically",
    "relicensing",
    "restaging",
    "ribtoks",
    "rustfmt",
    "rustlib",
    "rustup",
    "sanitization",
    "sed",
    "seg",
    "serde",
    "shellcheck",
    "shlex",
    "signable",
    "smallvec",
    "softprops",
    "ssim",
    "supersampled",
    "supersampling",
    "syscall",
    "taiki",
    "takedown",
    "testkey",
    "testsecret",
    "thiserror",
    "tmpl",
    "tsinis",
    "udeps",
    "umask",
    "unconflicted",
    "unfreed",
    "uninit",
    "unmatch",
    "unparseable",
    "untracking",
    "untracks",
    "xss",
    "xyz",
    "xzf",
    "yamllint",
    "zeroize",
]
ignore_paths = ["Cargo.lock", "**/LICENSE-*"]
