words = [
    "AGPL",
    "ASAN",
    "BITBUCKET",
    "BITRISE",
    "BUSL",
    "Bitbucket",
    "Bitrise",
    "CIRCLECI",
    "Codemagic",
    "DYLD",
    "Licensor",
    "RAII",
    "RUSTFLAGS",
    "RUSTSEC",
    "SOURCEBRANCHNAME",
    "Zmiri",
    "acb",
    "acd",
    "actionlint",
    "afbe",
    "atx",
    "bbd",
    "bbeafaf",
    "bcb",
    "bcb",
    "bcbd",
    "beb",
    "bfe",
    "blopker",
    "bytemuck",
    "caed",
    "cafa",
    "cbb",
    "cdf",
    "ceec",
    "cfa",
    "cinis",
    "cli",
    "clippy",
    "codecov",
    "cov",
    "dcacd",
    "ddae",
    "ddba",
    "ddf",
    "defe",
    "dfbc",
    "dhash",
    "docstrings",
    "eba",
    "ebbea",
    "ebe",
    "ebf",
    "eecfd",
    "efc",
    "fbde",
    "fcb",
    "fcd",
    "gfm",
    "gitleaks",
    "gix",
    "gleon",
    "globset",
    "goldens",
    "lcov",
    "learnings",
    "librustc",
    "markdownlint",
    "memcmp",
    "miri",
    "nextest",
    "oob",
    "phash",
    "powerset",
    "programmatically",
    "rustfmt",
    "rustlib",
    "rustup",
    "serde",
    "shellcheck",
    "smallvec",
    "ssim",
    "thiserror",
    "tsinis",
    "udeps",
    "xyz",
    "xzf",
    "yamllint",
]
ignore_paths = ["Cargo.lock"]
