//! Baseline approval operation for replacing snapshots with actual run images.

use crate::context::ResolvedContext;
use crate::manifest::ManifestError;
use crate::ops::common::{
    CoreError, build_manifest, ensure_initialized, hash_and_measure, load_index_with_fallback,
    platform_key,
};
use rayon::prelude::*;
use std::path::{Path, PathBuf};
use thiserror::Error;

struct ApprovedItem {
    test_name: String,
    raw_png_bytes: Vec<u8>,
    sha256_hex: String,
    phash_str: String,
    width: u32,
    height: u32,
}

const MAX_IMAGE_FILE_SIZE: u64 = 64 * 1024 * 1024; // 64 MB

/// Reads, size-checks, decodes, and hashes one approval candidate screenshot.
///
/// Pulled out of `approve_workspace`'s bounded-parallel batch loop so the per-file
/// read/validate/hash logic reads as its own unit rather than an anonymous closure body.
fn process_approve_candidate(
    test_name: &str,
    file_path: &Path,
    rel_to_source: &Path,
) -> Result<ApprovedItem, ApproveError> {
    use std::io::Read;
    let mut file = std::fs::File::open(file_path).map_err(CoreError::Io)?;
    let metadata = file.metadata().map_err(CoreError::Io)?;
    if metadata.len() > MAX_IMAGE_FILE_SIZE {
        return Err(ApproveError::ImageTooLarge {
            path: rel_to_source.to_path_buf(),
            size: metadata.len(),
            limit: MAX_IMAGE_FILE_SIZE,
        });
    }

    // Safe: metadata.len() was just checked against MAX_IMAGE_FILE_SIZE (64 MB) above,
    // which fits in a usize on every supported target.
    #[allow(clippy::cast_possible_truncation)]
    let mut raw_png_bytes = Vec::with_capacity(metadata.len() as usize);
    let bytes_read = (&mut file)
        .take(MAX_IMAGE_FILE_SIZE + 1)
        .read_to_end(&mut raw_png_bytes)
        .map_err(CoreError::Io)? as u64;

    if bytes_read > MAX_IMAGE_FILE_SIZE {
        return Err(ApproveError::ImageTooLarge {
            path: rel_to_source.to_path_buf(),
            size: bytes_read,
            limit: MAX_IMAGE_FILE_SIZE,
        });
    }

    let (sha256_hex, phash_str, width, height) =
        hash_and_measure(&raw_png_bytes).map_err(|e| match e {
            ManifestError::Image(source) => ApproveError::ImageDecode {
                path: rel_to_source.to_path_buf(),
                source,
            },
            other => CoreError::Manifest(other).into(),
        })?;

    Ok(ApprovedItem {
        test_name: test_name.to_string(),
        raw_png_bytes,
        sha256_hex,
        phash_str,
        width,
        height,
    })
}

/// Errors that can occur during baseline approval.
#[derive(Debug, Error)]
pub enum ApproveError {
    /// Multiple source paths resolved to the same canonical test name.
    #[error(
        "Duplicate test case name '{test_name}' generated by conflicting paths:\n  - {path1}\n  - {path2}"
    )]
    DuplicateTestName {
        /// The test name both paths normalized to.
        test_name: String,
        /// The first source path that produced this test name.
        path1: PathBuf,
        /// The second, conflicting source path.
        path2: PathBuf,
    },

    /// No actual screenshots found to approve at the target path.
    #[error("No actual screenshots found at path '{path}'")]
    NoActualScreenshots {
        /// The path that was scanned for screenshots.
        path: PathBuf,
    },

    /// Image file exceeds maximum allowed size.
    #[error("Image file '{path}' exceeds maximum size of {limit} bytes (actual: {size} bytes)")]
    ImageTooLarge {
        /// The path to the oversized image.
        path: PathBuf,
        /// The image's actual size in bytes.
        size: u64,
        /// The maximum allowed size in bytes.
        limit: u64,
    },

    /// Error decoding image file.
    #[error("Image decode error for '{path}'")]
    ImageDecode {
        /// The path to the image that failed to decode.
        path: PathBuf,
        /// The underlying decode error.
        #[source]
        source: image::ImageError,
    },

    /// Error shared across `ops::*` operations.
    #[error(transparent)]
    Core(#[from] CoreError),
}

/// Result summary of approving screenshots.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ApproveResult {
    /// List of test case names approved.
    pub approved_test_cases: Vec<String>,
    /// Number of total screenshots approved.
    pub total_approved: usize,
}

/// Executes approval pipeline to promote actual screenshots into baseline manifests and blobs.
///
/// # Errors
///
/// Returns an error if the workspace is not initialized, if the source directory (either
/// `from_dir` or the default `.gleon/runs/latest/actual`) does not exist or contains no PNG
/// screenshots, if two screenshots normalize to the same canonical test name, if any
/// screenshot exceeds the maximum allowed size or fails to decode, or if reading/writing
/// configuration, manifests, blobs, or other filesystem/JSON data fails.
// Genuinely long from three sequential, independent passes (walk+dedup test names, bounded
// parallel decode+hash, manifest/blob persistence with fallback-aware pruning), not from
// duplicated logic — see ops/common.rs for the helpers that already factor out what *is* shared
// with other operations.
#[allow(clippy::too_many_lines)]
pub fn approve_workspace(
    context: &ResolvedContext,
    paths: &[PathBuf],
    from_dir: Option<&Path>,
) -> Result<ApproveResult, ApproveError> {
    const BATCH_SIZE: usize = 32;

    let base_dir = context.base_dir.as_path();
    let gleon_paths = ensure_initialized(base_dir)?;

    let source_dir = from_dir.map_or_else(
        || gleon_paths.runs_actual(),
        |d| {
            if d.is_absolute() {
                d.to_path_buf()
            } else {
                base_dir.join(d)
            }
        },
    );

    match std::fs::metadata(&source_dir) {
        Ok(_) => {}
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return Err(ApproveError::NoActualScreenshots { path: source_dir });
        }
        Err(e) => return Err(CoreError::Io(e).into()),
    }

    let platform_key = platform_key(context)?;
    let blobs_dir = gleon_paths.blob_scheme_dir("sha256");
    let manifests_dir = gleon_paths.manifests_dir(&platform_key);
    std::fs::create_dir_all(&blobs_dir).map_err(CoreError::Io)?;
    std::fs::create_dir_all(&manifests_dir).map_err(CoreError::Io)?;

    let (mut workspace_index, fallback_index) = load_index_with_fallback(
        &gleon_paths,
        &platform_key,
        context.fallback_platform_key.as_deref(),
    )?;

    let mut candidate_files = Vec::new();
    let walker = ignore::WalkBuilder::new(&source_dir)
        .standard_filters(false)
        .filter_entry(|e| {
            if e.depth() > 0
                && e.file_type().is_some_and(|ft| ft.is_dir())
                && matches!(e.file_name().to_str(), Some(name) if name.starts_with('.') || crate::naming::DEFAULT_PRUNED_DIRECTORIES.contains(&name))
            {
                return false;
            }
            true
        })
        .build();

    for result in walker {
        let entry = match result {
            Ok(e) => e,
            Err(e) => {
                let msg = e.to_string();
                let io_err = e
                    .into_io_error()
                    .unwrap_or_else(|| std::io::Error::other(msg));
                return Err(CoreError::Io(io_err).into());
            }
        };
        let path = entry.path();
        let is_symlink = entry.file_type().is_some_and(|ft| ft.is_symlink());
        if !is_symlink
            && path.is_file()
            && path
                .extension()
                .and_then(|ext| ext.to_str())
                .is_some_and(|e| e.eq_ignore_ascii_case("png"))
        {
            candidate_files.push(path.to_path_buf());
        }
    }

    if candidate_files.is_empty() {
        return Err(ApproveError::NoActualScreenshots { path: source_dir });
    }

    // Pass 1: Resolve all canonical test names and filter paths, catching duplicates.
    let mut resolved_tests = std::collections::BTreeMap::new();
    let mut files_to_process = Vec::new();

    for file_path in candidate_files {
        let Ok(rel_to_source) = file_path.strip_prefix(&source_dir) else {
            continue;
        };

        // Apply path filter if provided (matching on exact component boundaries)
        if !paths.is_empty() {
            let rel_without_ext = rel_to_source.with_extension("");
            let matches_filter = paths
                .iter()
                .any(|p| rel_to_source.starts_with(p) || rel_without_ext.starts_with(p));
            if !matches_filter {
                continue;
            }
        }

        // Derive the canonical test name exactly the way `FileScanner` does for the same file:
        // strip the extension, normalize separators, fold case. Hand-rolling it here (stripping
        // a hardcoded `".png"` by byte offset) both risked slicing a multi-byte filename and
        // would silently disagree with the scanner the moment another input format is accepted,
        // filing approved baselines under a name `diff`/`status` never look up.
        let without_ext = rel_to_source.with_extension("");
        // `normalize_path_str` already folds case and separators into a canonical test name.
        let test_name = crate::scanner::FileScanner::normalize_path_str(&without_ext).into_owned();

        let rel_to_source_buf = rel_to_source.to_path_buf();
        if let Some(existing_path) = resolved_tests.insert(test_name.clone(), file_path.clone()) {
            return Err(ApproveError::DuplicateTestName {
                test_name,
                path1: existing_path,
                path2: file_path,
            });
        }
        files_to_process.push((test_name, file_path, rel_to_source_buf));
    }

    // Pass 2 & 3: Bounded parallel decoding, hashing, and manifest/blob saving
    let mut approved_test_cases = Vec::new();
    let mut total_approved = 0;

    for chunk in files_to_process.chunks(BATCH_SIZE) {
        let processed_items: Result<Vec<ApprovedItem>, ApproveError> = chunk
            .into_par_iter()
            .map(|(test_name, file_path, rel_to_source)| {
                process_approve_candidate(test_name, file_path, rel_to_source)
            })
            .collect();

        let processed_items = processed_items?;

        for item in processed_items {
            let blob_path = blobs_dir.join(&item.sha256_hex);
            crate::io::save_file_atomically(&blob_path, &item.raw_png_bytes)
                .map_err(CoreError::from)?;

            let new_manifest =
                build_manifest(&item.sha256_hex, &item.phash_str, item.width, item.height)?;

            let matches_fallback = fallback_index
                .as_ref()
                .and_then(|fb| fb.get(&item.test_name))
                .is_some_and(|fb_manifest| fb_manifest.hash == new_manifest.hash);

            if matches_fallback {
                // If a local override existed on disk, remove it to keep repository sparse
                let _ = workspace_index
                    .remove_test(&manifests_dir, &item.test_name)
                    .map_err(CoreError::Manifest)?;
                tracing::debug!(
                    "Approved test '{}' matches fallback platform manifest — pruned/skipped local override.",
                    item.test_name
                );
            } else {
                workspace_index
                    .save_test(&manifests_dir, &item.test_name, &new_manifest)
                    .map_err(CoreError::Manifest)?;
            }

            approved_test_cases.push(item.test_name);
            total_approved += 1;
        }
    }

    Ok(ApproveResult {
        approved_test_cases,
        total_approved,
    })
}

#[cfg(all(test, not(miri)))]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::missing_panics_doc,
    clippy::missing_errors_doc,
    clippy::pedantic,
    clippy::nursery
)]
mod tests {
    use super::*;
    use crate::config::ConfigError;
    use crate::context::ContextError;
    use crate::manifest::{ImageHash, SingleTestManifest};
    use crate::scanner::ScannerError;
    use sha2::{Digest, Sha256};

    #[test]
    fn test_approve_error_display() {
        let err1: ApproveError = CoreError::NotInitialized.into();
        assert!(err1.to_string().contains("not initialized"));

        let err2 = ApproveError::NoActualScreenshots {
            path: PathBuf::from("foo"),
        };
        assert!(err2.to_string().contains("No actual screenshots found"));
        assert!(err2.to_string().contains("foo"));

        let err3: ApproveError = CoreError::Context(ContextError::Platform(
            crate::platform::PlatformError::InvalidSegment("test".to_string()),
        ))
        .into();
        assert!(err3.to_string().contains("Context resolution error"));

        let err4: ApproveError = CoreError::Scanner(ScannerError::InvalidTestName {
            name: "bad".to_string(),
            reason: "reason".to_string(),
        })
        .into();
        assert!(err4.to_string().contains("Scanner error"));

        let err5: ApproveError =
            CoreError::Config(ConfigError::Validation("bad".to_string())).into();
        assert!(err5.to_string().contains("Config error"));

        let err6: ApproveError =
            CoreError::Manifest(ManifestError::Validation("bad".to_string())).into();
        assert!(err6.to_string().contains("Manifest error"));

        let img_err = image::ImageError::Limits(image::error::LimitError::from_kind(
            image::error::LimitErrorKind::DimensionError,
        ));
        let err7 = ApproveError::ImageDecode {
            path: PathBuf::from("bar.png"),
            source: img_err,
        };
        assert!(
            err7.to_string()
                .contains("Image decode error for 'bar.png'")
        );

        let err_too_large = ApproveError::ImageTooLarge {
            path: PathBuf::from("large.png"),
            size: 70 * 1024 * 1024,
            limit: 64 * 1024 * 1024,
        };
        assert!(err_too_large.to_string().contains("exceeds maximum size"));

        let err8: ApproveError = CoreError::Io(std::io::Error::other("io test")).into();
        assert!(err8.to_string().contains("IO error"));
    }

    #[test]
    fn test_approve_result_derived() {
        let res = ApproveResult {
            approved_test_cases: vec!["test1".to_string()],
            total_approved: 1,
        };
        let cloned = res.clone();
        assert_eq!(res, cloned);
        assert!(format!("{res:?}").contains("test1"));
    }

    #[test]
    fn test_approve_not_initialized() {
        let temp = tempfile::tempdir().unwrap();
        let ctx = ResolvedContext {
            base_dir: temp.path().to_path_buf(),
            ..ResolvedContext::default()
        };
        let res = approve_workspace(&ctx, &[], None);
        assert!(matches!(
            res,
            Err(ApproveError::Core(CoreError::NotInitialized))
        ));
    }

    #[test]
    fn test_approve_no_actual_dir() {
        let temp = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(temp.path().join(".gleon")).unwrap();
        let ctx = ResolvedContext {
            base_dir: temp.path().to_path_buf(),
            ..ResolvedContext::default()
        };
        let res = approve_workspace(&ctx, &[], None);
        assert!(matches!(res, Err(ApproveError::NoActualScreenshots { .. })));
    }

    #[test]
    fn test_approve_success_and_filtering() {
        let temp = tempfile::tempdir().unwrap();
        let gleon_dir = temp.path().join(".gleon");
        let actual_dir = gleon_dir.join("runs").join("latest").join("actual");

        let auth_dir = actual_dir.join("auth");
        let settings_dir = actual_dir.join("settings");
        std::fs::create_dir_all(&auth_dir).unwrap();
        std::fs::create_dir_all(&settings_dir).unwrap();

        let img = image::RgbaImage::new(10, 10);
        img.save(auth_dir.join("login.png")).unwrap();
        img.save(settings_dir.join("profile.png")).unwrap();

        let ctx = ResolvedContext {
            base_dir: temp.path().to_path_buf(),
            ..ResolvedContext::default()
        };

        // 1. Approve only auth test
        let res_filtered = approve_workspace(&ctx, &[PathBuf::from("auth")], None).unwrap();

        assert_eq!(res_filtered.total_approved, 1);
        assert_eq!(
            res_filtered.approved_test_cases,
            vec!["auth/login".to_string()]
        );

        // Verify blob and manifest created
        let plat_key = ctx.platform.to_key().unwrap();
        let manifests_dir = gleon_dir.join("manifests").join(&plat_key);
        assert!(manifests_dir.join("auth/login.json").exists());

        // 2. Approve all tests from custom --from directory
        let custom_dir = temp.path().join("custom_actual_images");
        let billing_dir = custom_dir.join("billing");
        std::fs::create_dir_all(&billing_dir).unwrap();
        img.save(billing_dir.join("checkout.png")).unwrap();

        let res_custom = approve_workspace(&ctx, &[], Some(&custom_dir)).unwrap();

        assert_eq!(res_custom.total_approved, 1);
        assert_eq!(
            res_custom.approved_test_cases,
            vec!["billing/checkout".to_string()]
        );
        assert!(manifests_dir.join("billing/checkout.json").exists());
    }

    #[test]
    fn test_approve_path_filtering_boundaries() {
        let temp = tempfile::tempdir().unwrap();
        let gleon_dir = temp.path().join(".gleon");
        let actual_dir = gleon_dir.join("runs").join("latest").join("actual");

        let auth_dir = actual_dir.join("auth");
        let author_dir = actual_dir.join("author");
        std::fs::create_dir_all(&auth_dir).unwrap();
        std::fs::create_dir_all(&author_dir).unwrap();

        let img = image::RgbaImage::new(10, 10);
        img.save(auth_dir.join("login.png")).unwrap();
        img.save(author_dir.join("profile.png")).unwrap();

        let ctx = ResolvedContext {
            base_dir: temp.path().to_path_buf(),
            ..ResolvedContext::default()
        };

        // Filtering by "auth" should match "auth/login.png" but NOT "author/profile.png"
        let res = approve_workspace(&ctx, &[PathBuf::from("auth")], None).unwrap();

        assert_eq!(res.total_approved, 1);
        assert_eq!(res.approved_test_cases, vec!["auth/login".to_string()]);
    }

    #[test]
    fn test_approve_validate_dimensions() {
        assert!(SingleTestManifest::validate_dimensions(0, 100).is_err());
        assert!(SingleTestManifest::validate_dimensions(100, 0).is_err());
        assert!(SingleTestManifest::validate_dimensions(16385, 100).is_err());
        assert!(SingleTestManifest::validate_dimensions(100, 16385).is_err());
        assert!(SingleTestManifest::validate_dimensions(16384, 4000).is_ok());
        assert!(SingleTestManifest::validate_dimensions(16384, 16384).is_err());
    }

    #[test]
    #[cfg(target_os = "linux")]
    fn test_approve_duplicate_test_name() {
        let temp = tempfile::tempdir().unwrap();
        let gleon_dir = temp.path().join(".gleon");
        let actual_dir = gleon_dir.join("runs").join("latest").join("actual");
        std::fs::create_dir_all(&actual_dir).unwrap();

        let img = image::RgbaImage::new(1, 1);
        // On Linux, these are two distinct files, but they normalize to "foo"
        img.save(actual_dir.join("foo.png")).unwrap();
        img.save(actual_dir.join("FOO.png")).unwrap();

        let ctx = ResolvedContext {
            base_dir: temp.path().to_path_buf(),
            ..ResolvedContext::default()
        };
        let res = approve_workspace(&ctx, &[], None);
        assert!(matches!(res, Err(ApproveError::DuplicateTestName { .. })));
    }

    #[test]
    fn test_approve_empty_actual_dir() {
        let temp = tempfile::tempdir().unwrap();
        let gleon_dir = temp.path().join(".gleon");
        let actual_dir = gleon_dir.join("runs").join("latest").join("actual");
        std::fs::create_dir_all(&actual_dir).unwrap();

        // Put a non-png file to verify it ignores it and still errors empty
        std::fs::write(actual_dir.join("test.txt"), "hello").unwrap();

        let ctx = ResolvedContext {
            base_dir: temp.path().to_path_buf(),
            ..ResolvedContext::default()
        };
        let res = approve_workspace(&ctx, &[], None);
        assert!(matches!(res, Err(ApproveError::NoActualScreenshots { .. })));
    }

    #[test]
    fn test_approve_image_decode_error() {
        let temp = tempfile::tempdir().unwrap();
        let gleon_dir = temp.path().join(".gleon");
        let actual_dir = gleon_dir.join("runs").join("latest").join("actual");
        std::fs::create_dir_all(&actual_dir).unwrap();

        // Valid PNG but truncated so load_from_memory fails but read_info succeeds
        let mut buf = Vec::new();
        let img = image::RgbaImage::new(1, 1);
        img.write_to(&mut std::io::Cursor::new(&mut buf), image::ImageFormat::Png)
            .unwrap();
        // Truncate the 12-byte IEND chunk (and possibly more) to cause decode error
        buf.truncate(buf.len() - 15);
        std::fs::write(actual_dir.join("test.png"), &buf).unwrap();

        let ctx = ResolvedContext {
            base_dir: temp.path().to_path_buf(),
            ..ResolvedContext::default()
        };
        let res = approve_workspace(&ctx, &[], None);
        assert!(matches!(res, Err(ApproveError::ImageDecode { .. })));
    }

    #[test]
    #[cfg(all(unix, not(miri)))]
    fn test_approve_rejects_symlinks() {
        let temp = tempfile::tempdir().unwrap();
        let gleon_dir = temp.path().join(".gleon");
        let actual_dir = gleon_dir.join("runs").join("latest").join("actual");
        std::fs::create_dir_all(&actual_dir).unwrap();

        let real_png = temp.path().join("real.png");
        let img = image::RgbaImage::new(1, 1);
        img.save(&real_png).unwrap();

        std::os::unix::fs::symlink(&real_png, actual_dir.join("symlink.png")).unwrap();

        let ctx = ResolvedContext {
            base_dir: temp.path().to_path_buf(),
            ..ResolvedContext::default()
        };
        let res = approve_workspace(&ctx, &[], None);
        assert!(matches!(res, Err(ApproveError::NoActualScreenshots { .. })));
    }

    #[test]
    fn test_approve_mixed_case_png_extension() {
        let temp = tempfile::tempdir().unwrap();
        let gleon_dir = temp.path().join(".gleon");
        let actual_dir = gleon_dir.join("runs").join("latest").join("actual");
        std::fs::create_dir_all(&actual_dir).unwrap();

        let img = image::RgbaImage::new(1, 1);
        img.save(actual_dir.join("test_case.PnG")).unwrap();

        let ctx = ResolvedContext {
            base_dir: temp.path().to_path_buf(),
            ..ResolvedContext::default()
        };
        let res = approve_workspace(&ctx, &[], None).unwrap();
        assert_eq!(res.total_approved, 1);
        assert_eq!(res.approved_test_cases, vec!["test_case".to_string()]);
    }

    #[test]
    #[cfg(all(unix, not(miri)))]
    fn test_approve_metadata_io_error_propagation() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempfile::tempdir().unwrap();
        let parent = temp.path().join("restricted");
        let gleon_dir = parent.join(".gleon");
        std::fs::create_dir_all(&gleon_dir).unwrap();

        let original_perms = std::fs::metadata(&parent).unwrap().permissions();
        std::fs::set_permissions(&parent, std::fs::Permissions::from_mode(0o000)).unwrap();

        let ctx = ResolvedContext {
            base_dir: parent.clone(),
            ..ResolvedContext::default()
        };
        let res = approve_workspace(&ctx, &[], None);

        let was_permission_denied = std::fs::metadata(&gleon_dir).is_err();
        let _ = std::fs::set_permissions(&parent, original_perms);

        if was_permission_denied {
            assert!(matches!(res, Err(ApproveError::Core(CoreError::Io(_)))));
        } else {
            // Superuser/root runners bypass 000 directory permissions
            assert!(res.is_err());
        }
    }

    #[test]
    fn test_approve_rejects_file_exceeding_max_size() {
        let temp = tempfile::tempdir().unwrap();
        let gleon_dir = temp.path().join(".gleon");
        let actual_dir = gleon_dir.join("runs").join("latest").join("actual");
        std::fs::create_dir_all(&actual_dir).unwrap();

        let large_file = actual_dir.join("too_large.png");
        let file = std::fs::File::create(&large_file).unwrap();
        file.set_len(65 * 1024 * 1024).unwrap();

        let ctx = ResolvedContext {
            base_dir: temp.path().to_path_buf(),
            ..ResolvedContext::default()
        };
        let res = approve_workspace(&ctx, &[], None);
        assert!(matches!(res, Err(ApproveError::ImageTooLarge { .. })));
    }

    #[test]
    fn test_approve_removes_redundant_override_when_matching_fallback() {
        let temp = tempfile::tempdir().unwrap();
        let base_path = temp.path();
        let gleon_dir = base_path.join(".gleon");
        let actual_dir = gleon_dir.join("runs").join("latest").join("actual");
        std::fs::create_dir_all(&actual_dir).unwrap();

        let linux_key = "5:linux-6:x86_64";
        let macos_key = "5:macos-7:aarch64";

        let ctx = ResolvedContext {
            base_dir: base_path.to_path_buf(),
            platform: crate::platform::PlatformInfo {
                os: "linux".to_string(),
                arch: Some("x86_64".to_string()),
                renderer: None,
                labels: std::collections::BTreeMap::new(),
            },
            fallback_platform_key: Some(macos_key.to_string()),
            ..Default::default()
        };

        // Create actual image (10x10) in actual_dir
        let img = image::RgbaImage::new(10, 10);
        let actual_file = actual_dir.join("test1.png");
        img.save(&actual_file).unwrap();
        let actual_bytes = std::fs::read(&actual_file).unwrap();
        let actual_sha = hex::encode(Sha256::digest(&actual_bytes));

        let dhash = ImageHash::new("dhash", "0000000000000000").unwrap();

        // 1. Fallback manifests (macos) contains test1 matching the actual image
        let macos_manifests_dir = gleon_dir.join("manifests").join(macos_key);
        std::fs::create_dir_all(&macos_manifests_dir).unwrap();
        let mac_manifest = SingleTestManifest::new(
            ImageHash::new("sha256", &actual_sha).unwrap(),
            dhash.clone(),
            10,
            10,
        )
        .unwrap();
        mac_manifest
            .save(macos_manifests_dir.join("test1.json"))
            .unwrap();

        // 2. Linux manifests contains an existing override with an OLD hash
        let linux_manifests_dir = gleon_dir.join("manifests").join(linux_key);
        std::fs::create_dir_all(&linux_manifests_dir).unwrap();
        let old_override = SingleTestManifest::new(
            ImageHash::new("sha256", "9".repeat(64)).unwrap(),
            dhash,
            10,
            10,
        )
        .unwrap();
        let linux_test_file = linux_manifests_dir.join("test1.json");
        old_override.save(&linux_test_file).unwrap();
        assert!(linux_test_file.exists());

        // Run approve on linux
        let res = approve_workspace(&ctx, &[], None).unwrap();
        assert_eq!(res.total_approved, 1);
        assert_eq!(res.approved_test_cases, vec!["test1".to_string()]);

        // Linux override must be removed from disk because it matches fallback
        assert!(!linux_test_file.exists());

        // Blob for actual_sha must exist
        assert!(
            gleon_dir
                .join("blobs")
                .join("sha256")
                .join(&actual_sha)
                .exists()
        );
    }

    #[test]
    fn test_approve_workspace_with_relative_custom_source_dir() {
        let temp = tempfile::tempdir().unwrap();
        let ctx = ResolvedContext {
            base_dir: temp.path().to_path_buf(),
            ..Default::default()
        };
        let gleon_paths = crate::paths::GleonPaths::new(temp.path());
        std::fs::create_dir_all(gleon_paths.manifests_root()).unwrap();

        let err = approve_workspace(&ctx, &[], Some(Path::new("relative_custom"))).unwrap_err();
        assert!(matches!(err, ApproveError::NoActualScreenshots { .. }));
    }
}
