name: spellcheck

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  spellcheck:
    name: 📝 Codebook Spellcheck
    runs-on: ubuntu-26.04

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v7.0.0

      - name: 📦 Install Codebook LSP
        run: |
          gh release download v0.3.41 --repo blopker/codebook --pattern '*linux*x86_64*' --output codebook.tar.gz
          tar -xzf codebook.tar.gz
          sudo mv codebook-lsp /usr/local/bin/
        env:
          GH_TOKEN: ${{ github.token }}

      - name: 🔍 Run Codebook Spellcheck
        run: codebook-lsp lint .
